# Assignment 5 - Risk
----
Risk
I love the board game Risk.Write a program (or notebook) called assignment_5_risk (.py or .ipynb)

The program should simulates 1000 individual battle rounds in Risk (3 attacker vs 2 defender) and plots the result.

One battle round is one shake of the attacker and defender dice.

I am being vague about what it plot, I will leave that to you.


=For the last few marks.=

A more complicated version simulates a full series of rounds for armies of arbitrary sizes, until one side is wiped out,

and plots the results.(This is open ended, so it is only for the last few marks)

**Rules of Risk**

In Risk one army fights another. (using 6 sided dice)

In each battle round, the attacker can put forward up to three of their troops (3 dice).

The defender can use up to two of their defending troops (2 dice).

Each side looses troops depending on the following rules:

The two top dice dice are compared (ie the attackers top dice roll with the defenders top dice roll) 
If the attackers dice is the same or lower they loose one troop otherwise the defender looses a troop (ie if the attackers dice is higher)
The next two highest dice from each side are then compared (ie the attackers second highest to the defenders second highest)
If the attackers dice is the same or lower they loose one troop otherwise the defender looses a troop (ie if the attackers dice is higher)


Examples
Attacker rolls	Defender Rolls	Attacker Loses	Defender Loses	Explanation
6,4,1	5,3	0	2	6 beats 5 and 4 beats 3 (the one is ignored as the lowest)
6,6,6	6,3	1	1	Defenders 6 beats the attackers first 6
and the attackers second 6 beats the defenders 3
5,4,4	5,4	2	0	The defenders 5 beat the attackers 5
and the defenders 4 beat the attackers 4
(defender wins when the dice are the same)

See the rules How to play Risk | Official Rules | UltraBoardGames
search "to decide a battle".

In [1]:
import numpy as np

In [2]:
dice = np.array([1, 2, 3, 4, 5, 6]) 

In [3]:
import random
rng = np.random.default_rng()

final_attacker = 0
final_defenders = 0
defenders= rng.choice(dice, size=(2)) # roll dice 2 times
attackers= rng.choice(dice, size=(3)) # roll dice 3 times.
a_high= np.max(attackers)
a_2high= np.median(attackers)
d_high= np.max(defenders)
d_2high= np.min(defenders)
result1 = a_high-d_high
result2 = a_2high-d_2high



def risk(result1, result2, final_attacker, final_defenders):
    if result1 == 0 and result2==0:
        print("Defenders, 2 points.")
        final_defenders +=2
    elif result1 == 0 and result2 < 0 or result2 == 0 and result1 < 0:
        print("Defenders, 2 points.")
        final_defenders +=2
    elif result1 == 0 and result2 > 0 or result2 == 0 and result1 > 0:
        print("Defender, 1 point, Attacker, 1 point.")
        final_defenders +=1
        final_attacker +=1
    elif result1 > 0 and result2 > 0:
        print("Attacker, 2 points.")
        final_attacker +=2
    elif result1 > 0 and result2 < 0:
        print("Attacker, 1 point, Defender, 1 point'")
        final_defenders +=1
        final_attacker +=1
    elif result1 < 0 and result2 > 0:
        print("Defender, 1 point, Attacker, 1 point.")
        final_defenders +=1
        final_attacker +=1
    else:  # both results are <0.
        print("Defenders, 2 points.")
        final_defenders +=2
    return result1, result2, final_defenders, final_attacker


def battle():
    defenders= rng.choice(dice, size=(2)) # roll dice 2 times
    attackers= rng.choice(dice, size=(3)) # roll dice 3 times.
    print(attackers)
    print(defenders)
    a_high= np.max(attackers)
    a_2high= int(np.median(attackers))
    d_high= np.max(defenders)
    d_2high= np.min(defenders)
    result1 = a_high-d_high
    result2 = a_2high-d_2high
    print(result1)
    print(result2)
    return risk(result1,result2, final_attacker, final_defenders)



for n in range(1000):
    battle()
    #print(battle())


[2 2 2]
[5 6]
-4
-3
Defenders, 2 points.
[3 3 4]
[5 2]
-1
1
Defender, 1 point, Attacker, 1 point.
[1 3 2]
[4 6]
-3
-2
Defenders, 2 points.
[3 1 4]
[2 1]
2
2
Attacker, 2 points.
[1 5 1]
[6 3]
-1
-2
Defenders, 2 points.
[5 3 2]
[5 6]
-1
-2
Defenders, 2 points.
[4 6 2]
[2 5]
1
2
Attacker, 2 points.
[2 6 6]
[5 1]
1
5
Attacker, 2 points.
[5 5 4]
[2 2]
3
3
Attacker, 2 points.
[1 6 6]
[2 4]
2
4
Attacker, 2 points.
[4 2 6]
[4 2]
2
2
Attacker, 2 points.
[6 3 1]
[6 1]
0
2
Defender, 1 point, Attacker, 1 point.
[5 6 3]
[5 1]
1
4
Attacker, 2 points.
[1 4 3]
[6 5]
-2
-2
Defenders, 2 points.
[4 4 3]
[3 3]
1
1
Attacker, 2 points.
[1 1 6]
[6 4]
0
-3
Defenders, 2 points.
[1 3 4]
[4 4]
0
-1
Defenders, 2 points.
[5 6 3]
[4 3]
2
2
Attacker, 2 points.
[4 2 1]
[1 4]
0
1
Defender, 1 point, Attacker, 1 point.
[2 4 1]
[1 6]
-2
1
Defender, 1 point, Attacker, 1 point.
[3 5 2]
[6 6]
-1
-3
Defenders, 2 points.
[1 2 5]
[6 3]
-1
-1
Defenders, 2 points.
[5 4 3]
[3 4]
1
1
Attacker, 2 points.
[1 2 2]
[6 6]
-4
-4
Defende

In [4]:
na= int(input("Number of attackers: "))
nd= int(input("Number of defenders: "))


def randombattle():
    attackers= rng.choice(dice, size=(na))
    defenders= rng.choice(dice, size=(nd))
    print(attackers)
    print(defenders)
    a_1= np.max(attackers)
    a_2= second_largest(attackers) 
    d_1= np.max(defenders)
    d_2= second_largest(defenders)
    randomresult1 = a_1-d_1
    randomresult2 = a_2-d_2
    print(randomresult1)
    print(randomresult2)
    return risk(randomresult1,randomresult2, final_attacker, final_defenders)


def second_largest(attackers):
    minimum = float('-inf')
    first, second = minimum, minimum
    for n in attackers:
        if n >= first:
            first, second = n, first
        elif first > n > second:
            second = n
    return second if second != minimum else None


def second_largest(defenders):
    minimum = float('-inf')
    first, second = minimum, minimum
    for n in defenders:
        if n >= first:
            first, second = n, first
        elif first > n > second:
            second = n
    return second if second != minimum else None

number_battles= int(input("Number of battles: "))

for n in range(number_battles):
    randombattle()
    #print(randombattle())

[2 2 1 4]
[6 1 2 1 4 1 1]
-2
-2
Defenders, 2 points.
[1 1 5 2]
[3 4 4 5 6 3 3]
-1
-3
Defenders, 2 points.
[5 6 6 4]
[4 2 4 1 2 6 5]
0
1
Defender, 1 point, Attacker, 1 point.


https://stackoverflow.com/questions/21598713/repeating-a-function-in-python

https://realpython.com/numpy-random-number-generator/#selecting-array-elements-randomly

https://realpython.com/numpy-max-maximum/#using-max

https://www.quora.com/How-do-I-repeat-a-function-in-Python

https://stackoverflow.com/questions/74795154/how-to-add-points-to-a-player-in-python

https://stackoverflow.com/questions/16225677/get-the-second-largest-number-in-a-list-in-linear-time