# Assignment 5 - Risk
---
Risk is a program that simulates 1000 individual battle rounds, where the team attacker is composed of 3 dice and the team defender with 2. The dice has 6 sides.

In the second part of this program, the user can choose the number of battle rounds between attacker and defender, and also determine the size of both teams.

**Rules of Risk**

In each battle round, the two top dice are compared, the attacker's top dice rolls with the defender's top dice. If the attacker's dice are the same or lower, they lose that round, otherwise, the defender loses. For the next round, the two highest dice from each side fight and the same rule is applied.

*Examples:*

Round 1|Attacker: 6,4,1|Defender: 5,3|Score: attacker 2, defender 0|

Attacker 6 beats Defender 5 and the attacker 4 beats the defender 3 (the one is ignored as the lowest).

Round 2|Attacker: 6,6,6|Defender: 6,3|Score: attacker 1, defender 1|

Defender 6 beats the attacker first 6 and the attacker second 6 beats the defender 3.

Round 3|Attacker: 5,4,4|Defender: 5,4|Score: attacker 0, defender 2|

The defender 5 beat the attacker 5 and the defender 4 beat the attacker 4 (the defender wins when the dice are the same).

This notebook can be run in the following link:
<a target="_blank" href="https://colab.research.google.com/github/FatimaBOliveira/Programming-for-data-analytics/blob/main/Assignments/assignment_5_risk.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>


## Simulation
First of all, the dice need to be defined, with the use of NumPy, it's possible to attribute 6 possible arrays, representing the 6 sides of the roll.

In [1]:
# Import NumPy library.
import numpy as np

In [2]:
# Dice has 6 sides.
dice = np.array([1, 2, 3, 4, 5, 6]) 

### Generate battles
To simulate a battle, it's essential to create a function that defines what a battle is. At the start, attackers and defenders are composed of many dice rolls, and those teams can be generated through [rng.choice](https://realpython.com/numpy-random-number-generator/#selecting-array-elements-randomly), and after that, I requested the machine to print the teams. Then, I calculated the highest rolls for each team to fight, and after the second-highest dice rolls will face each other. Finally, the machine will print the results of those encounters.

The battle function is dependent on 2 other functions, one to [calculate the second-highest dice roll](https://stackoverflow.com/questions/16225677/get-the-second-largest-number-in-a-list-in-linear-time/16226049#16226049), second_highest, and another one, risk, to determine who was the winner in each round, the attacker or the defender, attributing points to each team.

To [accumulate points](https://stackoverflow.com/questions/74795154/how-to-add-points-to-a-player-in-python) from the risk function, two new variables are needed, Attackers and Defenders, so these can be counted in the next step.

Now to generate 1000 battles, I use a [for loop](https://www.quora.com/How-do-I-repeat-a-function-in-Python), with the range representing the number of battles. Then to accumulate the points I checked how many points were received in each battle, and then added them together. Finally, the results are then printed.

In [3]:
# Random choice in both teams.
rng = np.random.default_rng()

# Definition of battle round.
def battle():
    attackers= rng.choice(dice, size=(3))
    defenders= rng.choice(dice, size=(2))
    print(attackers)
    print(defenders)
    a_high= np.max(attackers)
    a_2high= second_highest(attackers)
    d_high= np.max(defenders)
    d_2high= second_highest(defenders)
    result1 = a_high-d_high
    result2 = a_2high-d_2high
    print(result1)
    print(result2)
    return risk(result1,result2)

# Function to get the second highest value.
def second_highest(numbers):
    minimum = float("-inf")
    first, second = minimum, minimum
    for n in numbers:
        if n >= first:
            first, second = n, first
        elif first > n > second:
            second = n
    return second if second != minimum else None

# Points system.
def risk(result1, result2):
    attacker_points = 0
    defender_points = 0
    if result1 == 0 and result2 == 0:
        print("Defenders, 2 points.")
        defender_points += 2
    elif result1 == 0 and result2 < 0 or result2 == 0 and result1 < 0:
        print("Defenders, 2 points.")
        defender_points += 2
    elif result1 == 0 and result2 > 0 or result2 == 0 and result1 > 0:
        print("Defender, 1 point, Attacker, 1 point.")
        defender_points += 1
        attacker_points += 1
    elif result1 > 0 and result2 > 0:
        print("Attacker, 2 points.")
        attacker_points += 2
    elif result1 > 0 and result2 < 0:
        print("Attacker, 1 point, Defender, 1 point.")
        defender_points += 1
        attacker_points += 1
    elif result1 < 0 and result2 > 0:
        print("Defender, 1 point, Attacker, 1 point.")
        defender_points += 1
        attacker_points += 1
    else:  # both results are <0.
        print("Defenders, 2 points.")
        defender_points += 2
    return attacker_points, defender_points

# Track results.
Attackers= 0
Defenders= 0

# Simulate 1000 battle rounds and add points.
for n in range(1000):
    attacker_points, defender_points = battle()
    Attackers += attacker_points
    Defenders += defender_points


# Display the final results.
print(f"\nResults after 1000 dice battles:")
print(f"Attackers points: {Attackers}")
print(f"Defenders points: {Defenders}")

[3 2 2]
[3 3]
0
-1
Defenders, 2 points.
[5 4 6]
[4 5]
1
1
Attacker, 2 points.
[3 2 2]
[5 1]
-2
1
Defender, 1 point, Attacker, 1 point.
[5 5 5]
[3 1]
2
4
Attacker, 2 points.
[2 4 1]
[5 1]
-1
1
Defender, 1 point, Attacker, 1 point.
[2 4 5]
[2 1]
3
3
Attacker, 2 points.
[4 1 6]
[6 4]
0
0
Defenders, 2 points.
[4 6 6]
[4 5]
1
2
Attacker, 2 points.
[5 1 1]
[6 4]
-1
-3
Defenders, 2 points.
[1 5 6]
[5 2]
1
3
Attacker, 2 points.
[2 6 1]
[5 2]
1
0
Defender, 1 point, Attacker, 1 point.
[2 4 6]
[1 3]
3
3
Attacker, 2 points.
[2 5 2]
[4 5]
0
-2
Defenders, 2 points.
[1 4 3]
[2 5]
-1
1
Defender, 1 point, Attacker, 1 point.
[6 3 5]
[1 1]
5
4
Attacker, 2 points.
[6 5 6]
[1 2]
4
5
Attacker, 2 points.
[3 4 6]
[2 3]
3
2
Attacker, 2 points.
[3 2 1]
[1 4]
-1
1
Defender, 1 point, Attacker, 1 point.
[2 5 6]
[3 4]
2
2
Attacker, 2 points.
[3 6 6]
[6 1]
0
5
Defender, 1 point, Attacker, 1 point.
[3 4 3]
[4 4]
0
-1
Defenders, 2 points.
[3 3 2]
[4 3]
-1
0
Defenders, 2 points.
[1 6 4]
[2 1]
4
3
Attacker, 2 points.
[4

#### Part 2: User to choose team sizes and number of battles
For this part, I created three new variables that request input from the user, one asking for the number of attackers, another with the number of defenders, and finally the number of battles.

Then, to simulate a random battle, I used a function similar to battle, randombattle, only differing in the size of the teams.

The two variables, Attacker and Defenders, are called again to be reset to 0, so it won't count the battle points from above.

Finally, a for loop is used again but now with all the new inputs chosen by the user, number of attackers, defenders and battles. The results are then printed.

In [4]:
# Team sizes.
na= int(input("Number of attackers: "))
nd= int(input("Number of defenders: "))

# Definition of battle round, with random team sizes.
def randombattle():
    attackers= rng.choice(dice, size=(na))
    defenders= rng.choice(dice, size=(nd))
    print(attackers)
    print(defenders)
    a_high= np.max(attackers)
    a_2high= second_highest(attackers) 
    d_high= np.max(defenders)
    d_2high= second_highest(defenders)
    result1 = a_high-d_high
    result2 = a_2high-d_2high
    print(result1)
    print(result2)
    return risk(result1,result2)

# Track results.
Attackers = 0
Defenders = 0

# Number of battles.
number_battles= int(input("Number of battles: "))

# Simulate random battle rounds and add points.
for n in range(number_battles):
    attacker_points, defender_points = randombattle()
    Attackers += attacker_points
    Defenders += defender_points

# Display the final results.
print(f"\nResults after {number_battles} dice battles:")
print(f"Attackers points: {Attackers}")
print(f"Defenders points: {Defenders}")

[6 1 1 4 1 2]
[4 6 3 2 3]
0
0
Defenders, 2 points.
[4 1 6 2 1 6]
[6 4 2 4 5]
0
1
Defender, 1 point, Attacker, 1 point.
[5 1 3 1 3 6]
[4 3 1 1 4]
2
1
Attacker, 2 points.

Results after 3 dice battles:
Attackers points: 3
Defenders points: 3


___
## End