# Assignment 5 - Risk
----
Risk
I love the board game Risk.Write a program (or notebook) called assignment_5_risk (.py or .ipynb)

The program should simulates 1000 individual battle rounds in Risk (3 attacker vs 2 defender) and plots the result.

One battle round is one shake of the attacker and defender dice.

I am being vague about what it plot, I will leave that to you.


=For the last few marks.=

A more complicated version simulates a full series of rounds for armies of arbitrary sizes, until one side is wiped out,

and plots the results.(This is open ended, so it is only for the last few marks)

**Rules of Risk**

In Risk one army fights another. (using 6 sided dice)

In each battle round, the attacker can put forward up to three of their troops (3 dice).

The defender can use up to two of their defending troops (2 dice).

Each side looses troops depending on the following rules:

The two top dice dice are compared (ie the attackers top dice roll with the defenders top dice roll) 
If the attackers dice is the same or lower they loose one troop otherwise the defender looses a troop (ie if the attackers dice is higher)
The next two highest dice from each side are then compared (ie the attackers second highest to the defenders second highest)
If the attackers dice is the same or lower they loose one troop otherwise the defender looses a troop (ie if the attackers dice is higher)


Examples
Attacker rolls	Defender Rolls	Attacker Loses	Defender Loses	Explanation
6,4,1	5,3	0	2	6 beats 5 and 4 beats 3 (the one is ignored as the lowest)
6,6,6	6,3	1	1	Defenders 6 beats the attackers first 6
and the attackers second 6 beats the defenders 3
5,4,4	5,4	2	0	The defenders 5 beat the attackers 5
and the defenders 4 beat the attackers 4
(defender wins when the dice are the same)

See the rules How to play Risk | Official Rules | UltraBoardGames
search "to decide a battle".

In [1]:
import numpy as np

In [2]:
dice = np.array([1, 2, 3, 4, 5, 6]) 

In [3]:
rng = np.random.default_rng()

#input_array_1d = np.array([1, 2, 3, 4, 5, 6])
#rng.choice(input_array_1d, size=3, replace=False)

defenders= rng.choice(dice, size=(2)) # roll dice 2 times
# defenders= rng.choice(dice, size=(1000,2))
attackers= rng.choice(dice, size=(3)) # roll dice 3 times.
print(defenders)
print(attackers)

a_high= np.max(attackers)
a_low= np.min(attackers)
a_2high= np.median(attackers)
#attackers =[a_high,a_2high]

d_high= np.max(defenders)
d_2high= np.min(defenders)


result1 = a_high-d_high
result2 = a_2high-d_2high
print(result1)
print(result2)

[3 5]
[4 4 6]
1
1.0


In [21]:
def risk(result1, result2):
    if result1 == 0 and result2==0:
        print("Defenders, 2 points.")
    elif result1 == 0 and result2 < 0 or result2 == 0 and result1 < 0:
        print("Defenders, 2 points.")
    elif result1 == 0 and result2 > 0 or result2 == 0 and result1 > 0:
        print("Defender, 1 point, Attacker, 1 point.")
    elif result1 > 0 and result2 > 0:
        print("Attacker, 2 points.")
    elif result1 > 0 and result2 < 0:
        print("Attacker, 1 point, Defender, 1 point")
    elif result1 < 0 and result2 > 0:
        print("Defender, 1 point, Attacker, 1 point")
    else:  # both results are <0.
        print("Defenders, 2 points.")
    return result1, result2


print(risk(result1, result2))


Attacker, 2 points.
(1, 1.0)


In [23]:
rng = np.random.default_rng()

import random

def battle():
    defenders= rng.choice(dice, size=(2)) # roll dice 2 times
    attackers= rng.choice(dice, size=(3)) # roll dice 3 times.
    print(attackers)
    print(defenders)
    a_high= np.max(attackers)
    a_2high= np.median(attackers)
    d_high= np.max(defenders)
    d_2high= np.min(defenders)
    result1 = a_high-d_high
    result2 = a_2high-d_2high
    #print(result1)
    #print(result2)
    return risk(result1,result2)

#for sequence in battle():
#   print(sequence, end="\n")

for n in range(1000):
    print(battle())

#print(battle())

#print (risk(result1,result2))

[1 5 1]
[5 1]
Defenders, 2 points.
(0, 0.0)
[6 2 4]
[1 4]
Attacker, 2 points.
(2, 3.0)
[5 1 1]
[3 6]
Defenders, 2 points.
(-1, -2.0)
[1 6 1]
[4 6]
Defenders, 2 points.
(0, -3.0)
[6 1 4]
[1 5]
Attacker, 2 points.
(1, 3.0)
[6 2 4]
[3 6]
Defender, 1 point, Attacker, 1 point.
(0, 1.0)
[1 3 4]
[1 5]
Defender, 1 point, Attacker, 1 point
(-1, 2.0)
[5 5 4]
[6 3]
Defender, 1 point, Attacker, 1 point
(-1, 2.0)
[5 1 3]
[1 4]
Attacker, 2 points.
(1, 2.0)
[5 4 3]
[5 5]
Defenders, 2 points.
(0, -1.0)
[4 6 3]
[5 3]
Attacker, 2 points.
(1, 1.0)
[3 3 2]
[2 1]
Attacker, 2 points.
(1, 2.0)
[6 2 1]
[3 4]
Attacker, 1 point, Defender, 1 point
(2, -1.0)
[6 6 4]
[1 5]
Attacker, 2 points.
(1, 5.0)
[2 5 6]
[3 1]
Attacker, 2 points.
(3, 4.0)
[6 6 3]
[1 1]
Attacker, 2 points.
(5, 5.0)
[3 5 5]
[3 5]
Defender, 1 point, Attacker, 1 point.
(0, 2.0)
[5 5 2]
[2 6]
Defender, 1 point, Attacker, 1 point
(-1, 3.0)
[5 1 1]
[3 2]
Attacker, 1 point, Defender, 1 point
(2, -1.0)
[3 6 6]
[6 3]
Defender, 1 point, Attacker, 1 poin