# Assignment 5 - Risk
---
Risk is a program that simulates 1000 individual battle rounds, where the team attacker is composed of 3 dice and the team defender with 2. The dice has 6 sides.

**Rules of Risk**

In each battle round, the two top dice are compared, the attacker's top dice rolls with the defender's top dice. If the attacker's dice are the same or lower, they lose that round, otherwise, the defender loses. For the next round, the two highest dice from each side fight and the same rule is applied.

In the second part of this program, the user can choose the number of battle rounds between attacker and defender, and also determine the size of both teams. Each battle has 2 rounds as well.

*Examples:*

Round 1|Attacker: 6,4,1|Defender: 5,3|Score: attacker 2, defender 0|

Attacker 6 beats Defender 5 and the attacker 4 beats the defender 3.

Round 2|Attacker: 6,6,6|Defender: 6,3|Score: attacker 1, defender 1|

Defender 6 beats the attacker first 6 and the attacker second 6 beats the defender 3.

Round 3|Attacker: 5,4,4|Defender: 5,4|Score: attacker 0, defender 2|

The defender 5 beat the attacker 5 and the defender 4 beat the attacker 4.

This notebook can be run at the following link:<a target="_blank" href="https://colab.research.google.com/github/FatimaBOliveira/Programming-for-data-analytics/blob/main/Assignments/assignment_5_risk.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>


## Simulation
First of all, the dice need to be defined, with the use of NumPy, it's possible to attribute 6 possible arrays, representing the 6 sides of the dice.

In [1]:
# Import NumPy library.
import numpy as np

In [2]:
# Dice has 6 sides.
dice = np.array([1, 2, 3, 4, 5, 6]) 

### Generate battles
To simulate a battle, it's essential to create a function that defines what a battle is. At the start, the teams, attacker and defender, are composed of many dice rolls, and those teams can be generated through [rng.choice](https://realpython.com/numpy-random-number-generator/#selecting-array-elements-randomly). After that, the teams can be printed but to confirm that the teams are being correctly generated, but because it's generating 1000 battles, I decided to not show them, otherwise the output will be very long. Then, I calculated the highest rolls and put them to fight each other, and checked the second-highest dice rolls to face each other too. Finally, the machine can print the results of those encounters to confirm, but again I hid these to have a short output.

The battle function is dependent on 2 other functions, one to [calculate the second-highest dice roll](https://stackoverflow.com/questions/16225677/get-the-second-largest-number-in-a-list-in-linear-time/16226049#16226049), second_highest, and another one, risk, to attribute points for each team in every round and count the battle victories and the draws. To confirm the results of these battles, the print function can be used.

To [accumulate points](https://stackoverflow.com/questions/74795154/how-to-add-points-to-a-player-in-python) from the risk function, new variables are needed, two variables with the attacker and defender round points, another two with the victories and also one with the draws, so all of these can be counted in the next step.

Now to generate 1000 battles, I used a [for loop](https://www.quora.com/How-do-I-repeat-a-function-in-Python), with the range representing the number of battles. Then to accumulate the points, I checked how many points were received in each battle, and then added them to the variables. Finally, the results are then printed.

In [3]:
# Random choice in both teams.
rng = np.random.default_rng()

# Definition of battle round.
def battle():
    attacker= rng.choice(dice, size=(3))
    defender= rng.choice(dice, size=(2))
    #print(attacker)
    #print(defender)
    a_high= np.max(attacker)
    a_2high= second_highest(attacker)
    d_high= np.max(defender)
    d_2high= second_highest(defender)
    result1 = a_high-d_high
    result2 = a_2high-d_2high
    #print(result1)
    #print(result2)
    return risk(result1,result2)

# Function to get the second highest value.
def second_highest(numbers):
    minimum = float("-inf")
    first, second = minimum, minimum
    for n in numbers:
        if n >= first:
            first, second = n, first
        elif first > n > second:
            second = n
    return second if second != minimum else None

# Points system.
def risk(result1, result2):
    attacker_p = 0
    defender_p = 0
    a_v=0
    d_v=0
    draw=0
    if result1 == 0 and result2 == 0:
        #print("Defender, 2 points. Defender wins.")
        defender_p += 2
        d_v += 1
    elif result1 == 0 and result2 < 0 or result2 == 0 and result1 < 0:
        #print("Defender, 2 points. Defender wins.")
        defender_p += 2
        d_v += 1
    elif result1 == 0 and result2 > 0 or result2 == 0 and result1 > 0:
        #print("Defender, 1 point, Attacker, 1 point. Draw.")
        defender_p += 1
        attacker_p += 1
        draw += 1
    elif result1 > 0 and result2 > 0:
        #print("Attacker, 2 points. Attacker wins.")
        attacker_p +=2
        a_v +=1
    elif result1 > 0 and result2 < 0:
        #print("Attacker, 1 point, Defender, 1 point. Draw.")
        defender_p += 1
        attacker_p += 1
        draw += 1
    elif result1 < 0 and result2 > 0:
        #print("Defender, 1 point, Attacker, 1 point. Draw.")
        defender_p += 1
        attacker_p += 1
        draw += 1
    else:  # both results are <0.
        #print("Defender, 2 points. Defender wins.")
        defender_p += 2
        d_v += 1
    return attacker_p, defender_p, a_v, d_v, draw

# Track results.
attacker_points= 0
defender_points= 0
attacker_victory=0
defender_victory=0
draw_result=0

# Simulate 1000 battle rounds and add points.
for n in range(1000):
    attacker_p, defender_p, a_v, d_v, draw = battle()
    attacker_points += attacker_p
    defender_points += defender_p
    attacker_victory += a_v
    defender_victory += d_v
    draw_result += draw


# Display the final results.
print(f"\nResults after 1000 dice battles:")
print(f"Attacker points: {attacker_points}")
print(f"Defender points: {defender_points}")
print(f"Attacker victories: {attacker_victory}")
print(f"Defender victories: {defender_victory}")
print(f"Draws: {draw_result}")


Results after 1000 dice battles:
Attacker points: 1059
Defender points: 941
Attacker victories: 355
Defender victories: 296
Draws: 349


#### Part 2: User to choose team sizes and number of battles
For this part, I created three new variables that request input from the user, one asking for the number of elements for team attacker, another with the number of defenders, and finally the number of battles.

Then, to simulate a random battle, I used a function similar to battle, randombattle, only differing in the size of the teams. Each battle has 2 rounds, considering the highest and second-highest rolls as well. In this part, I decided to activate the print function so the user can see the output.

The five variables, attacker and defender points and victories and the draws, are called again to be reset to 0, so it won't count the battle points from above.

Finally, a for loop is used again but now with all the new inputs chosen by the user, number of attackers, defenders and battles. The results are then printed.

In [4]:
# Team sizes.
na= int(input("Number of attackers: "))
nd= int(input("Number of defenders: "))

# Definition of battle round, with random team sizes.
def randombattle():
    attacker= rng.choice(dice, size=(na))
    defender= rng.choice(dice, size=(nd))
    print(attacker)
    print(defender)
    a_high= np.max(attacker)
    a_2high= second_highest(attacker)
    d_high= np.max(defender)
    d_2high= second_highest(defender)
    result1 = a_high-d_high
    result2 = a_2high-d_2high
    print(result1)
    print(result2)
    return risk(result1,result2)

# Track results.
attacker_points= 0
defender_points= 0
attacker_victory=0
defender_victory=0
draw_result=0

# Number of battles.
number_battles= int(input("Number of battles: "))

# Simulate random battle rounds and add points.
for n in range(number_battles):
    attacker_p, defender_p, a_v, d_v, draw = randombattle()
    attacker_points += attacker_p
    defender_points += defender_p
    attacker_victory += a_v
    defender_victory += d_v
    draw_result += draw

# Display the final results.
print(f"\nResults after {number_battles} dice battles:")
print(f"Attacker points: {attacker_points}")
print(f"Defender points: {defender_points}")
print(f"Attacker victories: {attacker_victory}")
print(f"Defender victories: {defender_victory}")
print(f"Draw: {draw_result}")

[5 3 5 2 6 4 3]
[5 4 5 3 3]
1
0
[3 4 6 5 2 2 2]
[6 1 6 6 6]
0
-1
[1 1 4 3 3 6 1]
[3 2 1 2 1]
3
2
[1 1 5 1 2 1 3]
[3 2 1 2 5]
0
0
[4 3 3 5 1 5 1]
[3 2 1 1 1]
2
3

Results after 5 dice battles:
Attacker points: 5
Defender points: 5
Attacker victories: 2
Defender victories: 2
Draw: 1


___
## End